version: '3.8'

services:
  postgres:
    build:
      context: ./database
    ports:
      - "5432:5432"
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./database/postgres_data:/var/lib/postgresql/data  


  frontend:
    build:
      context: ./frontend
    ports:
      - "4173:4173"
    networks:
      - app_network
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
