# Generated by Django 5.1.2 on 2024-12-10 19:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('daily_meet_link', models.CharField(blank=True, max_length=500, null=True)),
                ('sprint_review', models.TextField(blank=True, max_length=5000, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_sprint', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=3000, null=True)),
                ('status', models.CharField(blank=True, max_length=60, null=True)),
                ('project_backlog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_backlog_tasks', to='projects.project')),
                ('sprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sprint_tasks', to='projects.sprint')),
            ],
        ),
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=3000, null=True)),
                ('status', models.CharField(blank=True, max_length=60, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('project_backlog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_backlog_history_tasks', to='projects.project')),
                ('sprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sprint_history_tasks', to='projects.sprint')),
                ('task_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_backlog_tasks', to='projects.task')),
            ],
        ),
    ]
