# Generated by Django 5.1.2 on 2024-12-10 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_sprint_task_taskhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskhistory',
            old_name='task_id',
            new_name='task',
        ),
    ]
