# Generated by Django 5.1.2 on 2025-01-05 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_taskhistory_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskhistory',
            name='estimated_hours',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
