# Generated by Django 5.1.2 on 2025-02-09 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_alter_task_estimated_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='manually_ended',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
