# Generated by Django 5.1.2 on 2025-02-11 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_sprint_manually_ended'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='title',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
