# Generated by Django 5.1.2 on 2025-02-11 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_sprint_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='title',
            field=models.TextField(blank=True, default=None, max_length=60, null=True),
        ),
    ]
