# Generated by Django 5.1.2 on 2025-04-12 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_task_approved_task_git_link_taskhistory_approved_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskhistory',
            name='sprint',
        ),
        migrations.RemoveField(
            model_name='task',
            name='sprint',
        ),
        migrations.RemoveField(
            model_name='task',
            name='project_backlog',
        ),
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
        migrations.RemoveField(
            model_name='taskhistory',
            name='task',
        ),
        migrations.RemoveField(
            model_name='taskhistory',
            name='project_backlog',
        ),
        migrations.RemoveField(
            model_name='taskhistory',
            name='user',
        ),
        migrations.AlterField(
            model_name='project',
            name='project_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Sprint',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='TaskHistory',
        ),
    ]
