# Generated by Django 5.1.2 on 2025-04-12 00:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0017_remove_taskhistory_sprint_remove_task_sprint_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.TextField(blank=True, default=None, max_length=60, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('daily_meet_link', models.CharField(blank=True, max_length=500, null=True)),
                ('sprint_review', models.TextField(blank=True, max_length=5000, null=True)),
                ('manually_ended', models.BooleanField(blank=True, default=False, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_sprint', to='projects.project')),
            ],
        ),
    ]
